# Optimise coeffs from DEAP output

Try to improve the existing best coefficients from the genetic algorithm results by running them through optimisation functions.

Try `scipy.optimize.minimize` and simuleated annealing.

__Inputs:__

+ MSOA-level admissions numbers, numbers of people in each age band, and deprivation quantile.
+ SSNAP-derived stroke admission coefficients (probability of stroke given age band).
+ Admission numbers in England by age band.

__Results:__

+ Data: optimised coefficients for the five top fits from the genetic algorithm.
  + File name: `post_deap_multi_optimise_coeffs_results.csv`
+ Data: optimised coefficients for all of the genetic algorithm output from simulated annealing (basin hopping).
  + File name: `post_deap_multi_basinhop_coeffs_results.csv`

__Method:__

Convert the genetic algorithm output from scale factors to the probability of stroke admission by multiplying them by the starting SSNAP coefficients.

First try just a straight minimisation with the five best results from the genetic algorithm, but see that the resulting coefficients don't change much so not a good method for this case - doubt we have bang on the best values to start with, expect them to change quite a bit.

Then try simulated annealing with all of the best outputs from the genetic algorithm.

This notebook just runs the optimisations. The results are checked in the next notebook.

In [1]:
import os
import polars as pl
from scipy.optimize import minimize, basinhopping
import numpy as np
import matplotlib.pyplot as plt

## Load data

Patient demographics by MSOA:

In [2]:
path_to_msoa_stats = os.path.join('data', 'msoa_cleaned.csv')

df_stats = pl.read_csv(path_to_msoa_stats)

In [3]:
df_stats.head()

shape: (5, 25)
┌──────────┬────────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ MSOA     ┆ admissions ┆ IMD2019Sc ┆ All       ┆ … ┆ age_75   ┆ age_over8 ┆ depriv_qu ┆ depriv_qu │
│ ---      ┆ ---        ┆ ore       ┆ persons   ┆   ┆ ---      ┆ 0         ┆ antile_mi ┆ antile_ma │
│ str      ┆ f64        ┆ ---       ┆ ---       ┆   ┆ f64      ┆ ---       ┆ n         ┆ x         │
│          ┆            ┆ f64       ┆ i64       ┆   ┆          ┆ f64       ┆ ---       ┆ ---       │
│          ┆            ┆           ┆           ┆   ┆          ┆           ┆ f64       ┆ f64       │
╞══════════╪════════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ Adur 001 ┆ 14.333333  ┆ 16.924833 ┆ 8815      ┆ … ┆ 371.993  ┆ 546.53    ┆ 0.4       ┆ 0.6       │
│ Adur 002 ┆ 7.333333   ┆ 6.4704    ┆ 7263      ┆ … ┆ 357.3396 ┆ 502.5996  ┆ 0.8       ┆ 1.0       │
│ Adur 003 ┆ 9.333333   ┆ 13.7334   ┆ 7354      ┆ … ┆ 309.6034 ┆ 486.0994  ┆ 0.6       ┆ 0.8       │
│ Adur 004 ┆ 21.0       ┆ 26.199857 ┆ 10582     ┆ … ┆ 388.3594 ┆ 675.1316  ┆ 0.2       ┆ 0.4       │
│ Adur 005 ┆ 13.666667  ┆ 11.7948   ┆ 9059      ┆ … ┆ 385.0075 ┆ 599.7058  ┆ 0.6       ┆ 0.8       │
└──────────┴────────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

Pick out column names for the health and age proportions:

In [4]:
health_numbers = ['good_health', 'fair health', 'bad health']
props_health = ['prop_good_health', 'prop_fair health', 'prop_bad health']
props_age = [
    'age_less65_proportion', 'age_65_proportion', 'age_70_proportion',
    'age_75_proportion', 'age_over80_proportion'
]
age_numbers = [p.replace('_proportion', '') for p in props_age]

In [5]:
qmin_list = sorted(df_stats['depriv_quantile_min'].unique())

In [6]:
# Names of coeffs:
coeff_names = [f'{a}_q{str(round(q, 1)).replace(".", "")}' for q in qmin_list for a in age_numbers]

coeff_names

['age_less65_q00',
 'age_65_q00',
 'age_70_q00',
 'age_75_q00',
 'age_over80_q00',
 'age_less65_q02',
 'age_65_q02',
 'age_70_q02',
 'age_75_q02',
 'age_over80_q02',
 'age_less65_q04',
 'age_65_q04',
 'age_70_q04',
 'age_75_q04',
 'age_over80_q04',
 'age_less65_q06',
 'age_65_q06',
 'age_70_q06',
 'age_75_q06',
 'age_over80_q06',
 'age_less65_q08',
 'age_65_q08',
 'age_70_q08',
 'age_75_q08',
 'age_over80_q08']

Pick out data for calculating admissions:

In [7]:
all_x_lists = []
all_admissions = []

for qmin in qmin_list:
    mask = (df_stats['depriv_quantile_min'] == qmin)
    # Keep only those MSOA:
    df_stats_here = df_stats.filter(mask)
    # MSOA data in the same order as those coefficients:
    x_lists = [df_stats_here[a] for a in age_numbers]
    admissions = df_stats_here['admissions'].to_numpy()
    all_x_lists.append(x_lists)
    all_admissions.append(admissions)

Starting SSNAP coefficients:

In [8]:
df_pop_admissions = pl.read_csv(os.path.join('outputs', 'ssnap_coeffs.csv'))

In [9]:
df_pop_admissions

shape: (5, 8)
┌────────────┬────────────┬────────────┬───────┬────────────┬────────────┬────────────┬────────────┐
│ Age Groups ┆ population ┆ prop_of_al ┆ count ┆ prop_of_al ┆ admissions ┆ admissions ┆ prob_strok │
│ ---        ┆ ---        ┆ l_pop      ┆ ---   ┆ l_admissio ┆ _annual    ┆ _annual_bo ┆ e_given_ag │
│ str        ┆ i64        ┆ ---        ┆ i64   ┆ ns         ┆ ---        ┆ ost        ┆ e          │
│            ┆            ┆ f64        ┆       ┆ ---        ┆ f64        ┆ ---        ┆ ---        │
│            ┆            ┆            ┆       ┆ f64        ┆            ┆ f64        ┆ f64        │
╞════════════╪════════════╪════════════╪═══════╪════════════╪════════════╪════════════╪════════════╡
│ Under 65   ┆ 45933245   ┆ 0.816055   ┆ 38827 ┆ 0.231449   ┆ 12942.3333 ┆ 18737.6681 ┆ 0.000408   │
│            ┆            ┆            ┆       ┆            ┆ 3          ┆ 9          ┆            │
│ 65-69      ┆ 2796740    ┆ 0.049687   ┆ 15324 ┆ 0.091347   ┆ 5108.0     ┆ 7395.26689 ┆ 0.002644   │
│ 70-74      ┆ 2779326    ┆ 0.049378   ┆ 21508 ┆ 0.12821    ┆ 7169.33333 ┆ 10379.6267 ┆ 0.003735   │
│            ┆            ┆            ┆       ┆            ┆            ┆ 4          ┆            │
│ 75-79      ┆ 1940686    ┆ 0.034478   ┆ 24150 ┆ 0.143959   ┆ 8050.0     ┆ 11654.6394 ┆ 0.006005   │
│            ┆            ┆            ┆       ┆            ┆            ┆ 8          ┆            │
│ 80 and     ┆ 2836964    ┆ 0.050402   ┆ 67947 ┆ 0.405035   ┆ 22649.0    ┆ 32790.7987 ┆ 0.011558   │
│ over       ┆            ┆            ┆       ┆            ┆            ┆            ┆            │
└────────────┴────────────┴────────────┴───────┴────────────┴────────────┴────────────┴────────────┘

Pick out SSNAP coefficients:

In [10]:
coeffs_ssnap = df_pop_admissions['prob_stroke_given_age'].to_numpy()

coeffs_ssnap

array([0.000408, 0.002644, 0.003735, 0.006005, 0.011558])

Pick out admissions numbers:

In [11]:
dict_admissions_age = dict(zip(df_pop_admissions['Age Groups'], df_pop_admissions['admissions_annual_boost']))

admissions_by_age = list(dict_admissions_age.values())

dict_admissions_age

{'Under 65': 18737.66819,
 '65-69': 7395.26689,
 '70-74': 10379.62674,
 '75-79': 11654.63948,
 '80 and over': 32790.7987}

## Gather starting coeffs

from best DEAP results

In [12]:
df_best_gens = pl.read_csv(os.path.join('outputs', 'best_inds_deap.csv'))

In [13]:
df_best_gens.sort('r2_all', descending=True)

shape: (100, 34)
┌──────────────┬───────┬──────────────┬────────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ dir          ┆ # gen ┆ age_less65_q ┆ age_65_q00 ┆ … ┆ r2_q02   ┆ r2_q04   ┆ r2_q06   ┆ r2_q08   │
│ ---          ┆ ---   ┆ 00           ┆ ---        ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str          ┆ f64   ┆ ---          ┆ f64        ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
│              ┆       ┆ f64          ┆            ┆   ┆          ┆          ┆          ┆          │
╞══════════════╪═══════╪══════════════╪════════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ randomseed36 ┆ 26.0  ┆ 1.276        ┆ 1.232      ┆ … ┆ 0.580221 ┆ 0.638502 ┆ 0.614997 ┆ 0.61723  │
│ randomseed95 ┆ 35.0  ┆ 1.329        ┆ 1.313      ┆ … ┆ 0.576829 ┆ 0.638087 ┆ 0.614718 ┆ 0.622301 │
│ randomseed73 ┆ 48.0  ┆ 1.3          ┆ 1.3        ┆ … ┆ 0.58256  ┆ 0.635348 ┆ 0.61498  ┆ 0.61906  │
│ randomseed52 ┆ 28.0  ┆ 1.3          ┆ 1.17       ┆ … ┆ 0.580277 ┆ 0.638502 ┆ 0.616117 ┆ 0.618497 │
│ randomseed10 ┆ 26.0  ┆ 1.299        ┆ 1.359      ┆ … ┆ 0.581876 ┆ 0.63755  ┆ 0.613672 ┆ 0.616852 │
│ …            ┆ …     ┆ …            ┆ …          ┆ … ┆ …        ┆ …        ┆ …        ┆ …        │
│ randomseed09 ┆ 46.0  ┆ 1.182        ┆ 1.2        ┆ … ┆ 0.577935 ┆ 0.637691 ┆ 0.615445 ┆ 0.611092 │
│ randomseed41 ┆ 35.0  ┆ 1.2          ┆ 1.2        ┆ … ┆ 0.575404 ┆ 0.633268 ┆ 0.614521 ┆ 0.620178 │
│ randomseed82 ┆ 21.0  ┆ 1.213        ┆ 1.268      ┆ … ┆ 0.578808 ┆ 0.632767 ┆ 0.615709 ┆ 0.611124 │
│ randomseed69 ┆ 28.0  ┆ 1.2          ┆ 1.235      ┆ … ┆ 0.583379 ┆ 0.636176 ┆ 0.61102  ┆ 0.605843 │
│ randomseed47 ┆ 27.0  ┆ 1.2          ┆ 1.2        ┆ … ┆ 0.57733  ┆ 0.631058 ┆ 0.613142 ┆ 0.603192 │
└──────────────┴───────┴──────────────┴────────────┴───┴──────────┴──────────┴──────────┴──────────┘

Pick out the directory names:

In [14]:
best_dirs = df_best_gens.sort('r2_all', descending=True)['dir'].to_numpy()

Pick out the coefficients for each of these directories:

In [15]:
# Store start combos of coeffs in here:
coeffs_init_start = {}
scales_init_start = {}

for d, best_dir in enumerate(best_dirs):
    scales_init = df_best_gens.filter(df_best_gens['dir'] == best_dir)[coeff_names].to_numpy()[0]
    coeffs_init = [s for s in scales_init]
    for c, coeff in enumerate(coeffs_ssnap):
        for i in range(5):
            coeffs_init[5*i + c] *= coeff
    coeffs_init_start[best_dir] = coeffs_init
    scales_init_start[best_dir] = scales_init

# coeffs_init_grid = np.array(coeffs_init).reshape(5, 5)
# # To get all coeffs for one age band:        coeffs_init_grid[:, 0]
# # To get all coeffs for one depriv quantile: coeffs_init_grid[0, :]

Convert dictionary to dataframe:

In [16]:
df_coeffs_init = pl.concat([pl.DataFrame([c], schema=coeff_names) for c in coeffs_init_start.values()]).cast(float)

df_coeffs_init = df_coeffs_init.with_columns(pl.Series('coeff_combo', coeffs_init_start.keys()))#.cast(int))
# Move this column to start:
df_coeffs_init = df_coeffs_init.drop('coeff_combo').insert_column(0, df_coeffs_init.get_column('coeff_combo'))

/home/anna/miniconda3/envs/stroke_lsoa_prediction/lib/python3.10/functools.py:889: DataOrientationWarning: Row orientation inferred during DataFrame construction. Explicitly specify the orientation by passing `orient="row"` to silence this warning.
  return dispatch(args[0].__class__)(*args, **kw)

Round results:

In [17]:
# labels = ['less65', '65', '70', '75', 'over80']
# round_dict = dict(zip(labels, [5, 4, 4, 4, 4]))

# for coeff in coeff_names:
#     key = coeff.split('_')[1]
#     new_data = np.round(df_coeffs_init[coeff], round_dict[key])
    
#     df_coeffs_init = df_coeffs_init.with_columns(pl.Series(coeff, new_data))

Check results:

In [18]:
df_coeffs_init

shape: (100, 26)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ coeff_com ┆ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ … ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ age_over │
│ bo        ┆ 5_q00     ┆ 0         ┆ 0         ┆   ┆ 8         ┆ 8         ┆ 8         ┆ 80_q08   │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ randomsee ┆ 0.000521  ┆ 0.003257  ┆ 0.004489  ┆ … ┆ 0.0023796 ┆ 0.002988  ┆ 0.004804  ┆ 0.01024  │
│ d36       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ randomsee ┆ 0.000542  ┆ 0.003472  ┆ 0.004661  ┆ … ┆ 0.002224  ┆ 0.0033615 ┆ 0.004876  ┆ 0.010402 │
│ d95       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2        │
│ randomsee ┆ 0.0005304 ┆ 0.0034372 ┆ 0.004549  ┆ … ┆ 0.002123  ┆ 0.002988  ┆ 0.004984  ┆ 0.010402 │
│ d73       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2        │
│ randomsee ┆ 0.0005304 ┆ 0.003093  ┆ 0.004482  ┆ … ┆ 0.002353  ┆ 0.003332  ┆ 0.004618  ┆ 0.010402 │
│ d52       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2        │
│ randomsee ┆ 0.00053   ┆ 0.003593  ┆ 0.004732  ┆ … ┆ 0.002197  ┆ 0.002988  ┆ 0.004804  ┆ 0.010402 │
│ d10       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ randomsee ┆ 0.000482  ┆ 0.0031728 ┆ 0.004482  ┆ … ┆ 0.0023796 ┆ 0.0033615 ┆ 0.005218  ┆ 0.009709 │
│ d09       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ randomsee ┆ 0.0004896 ┆ 0.0031728 ┆ 0.004519  ┆ … ┆ 0.0022474 ┆ 0.002988  ┆ 0.005074  ┆ 0.010402 │
│ d41       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2        │
│ randomsee ┆ 0.000495  ┆ 0.003353  ┆ 0.004325  ┆ … ┆ 0.0023796 ┆ 0.003317  ┆ 0.005405  ┆ 0.009593 │
│ d82       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ randomsee ┆ 0.0004896 ┆ 0.003265  ┆ 0.004482  ┆ … ┆ 0.0023796 ┆ 0.003309  ┆ 0.005122  ┆ 0.010159 │
│ d69       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ randomsee ┆ 0.0004896 ┆ 0.0031728 ┆ 0.004482  ┆ … ┆ 0.0023796 ┆ 0.003298  ┆ 0.005405  ┆ 0.010055 │
│ d47       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

Save a copy:

In [19]:
df_coeffs_init.write_csv(os.path.join('genetic_algorithms', 'outputs', 'post_deap_inputs_for_opt.csv'))

## Function for optimising

In [20]:
def main_opt(coeffs, args):
    all_calculated_admissions = []
    all_observed_admissions = sum([list(a) for a in args[1]], [])

    
    # Convert scales to coefficients: IF NECESSARY --------------------------------
    coeffs_init = coeffs * np.concatenate([coeffs_ssnap] * 5)
    
    coeffs = np.round(coeffs, 7)


    x_lists = args[0]
    admissions_by_age = args[2]
    # coeffs_ssnap = args[3]
    # Predictions for each age band across England:
    predictions_by_age = [0.0] * 5
    for i in range(5):
        # Population numbers for areas in this quantile:
        x_lists_here = x_lists[i]
        # Separate prediction for each deprivation quantile:
        coeffs_here = coeffs[(i*5):(i*5)+5] #* np.array(coeffs_ssnap)
        yhat_list = predict_admissions_each_age(x_lists_here, coeffs_here)
        # predictions_lists.append(yhat)
        for j, y in enumerate(yhat_list):
            predictions_by_age[j] += y
    # Divide the admissions by age band by the observed values:
    for j in range(len(predictions_by_age)):
        predictions_by_age[j] /= admissions_by_age[j]
    # Wrongness ratio factor:
    rat = sum(np.abs(np.array(predictions_by_age) - 1.0)) + 1.0

    
    coeffs_grid = np.array(coeffs).reshape(5, 5)
    for i, q in enumerate(qmin_list):
        coeffs_q = coeffs_grid[i, :]
        x_lists = args[0][i]
        admissions = args[1][i]
        
        calculated_admissions = predict_admissions(x_lists, np.array(coeffs_q))

        all_calculated_admissions += list(calculated_admissions)

    # Calculate measure of difference from the observed admissions:
    # print(
    #     np.array(all_calculated_admissions),
    #     np.array(all_observed_admissions)
    # )
    # diff = find_mean_abs_diff(
    diff = find_square_residuals(
        np.array(all_calculated_admissions),
        np.array(all_observed_admissions)
    )
    # Apply wrongness factor:
    diff *= rat

    
    diff_before = diff
    n_penalty = 0
    use_penalty = True
    if use_penalty:
        # Check coefficient conditions. If any aren't met, add a penalty
        # to the main difference measure.
        n_decrease = 0.0
        for i, q in enumerate(qmin_list):
            # Pick out coeffs for this depriv quantile:
            coeffs_q = coeffs_grid[i, :]
            # Do all coeffs increase with age band?
            n_decrease += sum(np.sign(np.diff(coeffs_q)) < 0)

        n_increase = 0.0
        for i, a in enumerate(age_numbers):
            # Pick out coeffs for this age band:
            coeffs_q = coeffs_grid[:, i]
            # Do all coeffs decrease with depriv quantile?
            n_increase += sum(np.sign(np.diff(coeffs_q)) > 0)

        # Add penalty:
        n_penalty = n_increase + n_decrease
        if n_penalty > 0.0:
            diff += (n_penalty * abs(diff) * 0.2)
    # print(diff_before, n_penalty, diff)
    # print(coeffs_grid)
    # # print(n_decrease, n_increase, diff)
    # print('\n' * 3)

    return diff

In [21]:
def predict_admissions(x_lists, coeffs):
    """
    x_lists: np.array.
    coeffs: np.array.
    
    Have to have same number of coeffs as x_lists.
    """
    # Predicted admissions:
    yhat = (x_lists * coeffs.reshape(len(coeffs), 1)).sum(axis=0)
    return yhat

In [22]:
def predict_admissions_each_age(x_lists, coeffs):
    """
    x_lists: np.array.
    coeffs: np.array.
    
    Have to have same number of coeffs as x_lists.
    """
    # Predicted admissions:
    # yhat = (x_lists * coeffs.reshape(len(coeffs), 1)).sum(axis=0)
    # yhat = [(x_lists[i] * coeffs[i]).to_numpy() for i in range(len(coeffs))]
    yhat = (
        [(x_lists[i] * coeffs[i]).sum() for i in range(len(coeffs))]
    )
    return yhat

Goodness check option 1: This calculates the sum of the square of the differences between predicted and actual admission numbers:

In [23]:
def find_square_residuals(yhat, y):
    # Difference from actual:
    sqres = (yhat - y)**2.0
    # Sum of differences:
    sum_sqres = np.sqrt(sqres.sum())
    return sum_sqres

Goodness check option 2: This calculates the mean absolute difference between the predicted and real admissions numbers:

In [24]:
def find_mean_abs_diff(yhat, y):
    # Difference from actual:
    absres = np.abs((yhat - y))
    # Mean of differences:
    mean_absres = absres.mean()
    return mean_absres

To check accuracy, the following function calculates R-squared:

In [25]:
def calculate_rsquared(y, yhat):
    """This gives the same results as the sklearn built-in."""
    y_mean = y.mean()
    ss_res = ((yhat - y)**2.0).sum()
    ss_tot = ((y - y_mean)**2.0).sum()
    if ss_tot != 0.0:
        rsq = 1.0 - ss_res / ss_tot
    else:
        rsq = np.NaN
    return rsq

## Run grid

In [151]:
best_dirs = df_best_gens.filter(np.round(df_best_gens['r2_all'], 3) == np.round(df_best_gens['r2_all'].max(), 3))['dir'].to_numpy()

# Only run these best starting coeffs:
coeffs_init_start_opt = {}

for k, v in coeffs_init_start.items():
    if k in best_dirs:
        coeffs_init_start_opt[k] = v
    else:
        pass

In [152]:
dict_coeffs = {}
dict_opt_results = {}
# Store these opt results keys:
opt_results_keys = ['message', 'success', 'status', 'nit', 'nfev']

i = 1
for coeff_combo, coeffs_init in coeffs_init_start_opt.items():
    print(f'{i:5d} out of {len(coeffs_init_start_opt)}', end='\r')
    i += 1
    bounds_here = [(0.0, 1.0)] * len(coeffs_init)  # force results to lie between 0 and 1
    
        
    # Run the optimiser:
    opt_results = minimize(
        main_opt,
        x0=coeffs_init,
        args=[all_x_lists, all_admissions, admissions_by_age],
        bounds=bounds_here,
        method='Nelder-Mead',
        # method='SLSQP',
        options=dict(maxiter=10000),
    )
    # Pick out the resulting health coefficients:
    coeffs = np.round(opt_results['x'], 7)

    # Calculate R^2 here:

    # Log whether this combo optimised successfully:
    dict_opt_results[coeff_combo] = pl.DataFrame(np.array([[f'{coeff_combo}'] + [opt_results[k] for k in opt_results_keys]]), schema=['coeff_combo'] + opt_results_keys)
    # pl.Series(f'{coeff_combo}', [opt_results[k] for k in opt_results_keys], strict=False).to_frame()
    # Store coeffs:
    dict_coeffs[coeff_combo] = pl.DataFrame(np.array([[f'{coeff_combo}'] + list(coeffs)]), schema=['coeff_combo'] + coeff_names)
    # pl.Series(f'{coeff_combo}', coeffs).to_frame()

KeyboardInterrupt:

Gather results into dataFrames:

In [ ]:
df_opt_results = pl.concat(dict_opt_results.values())

df_coeffs = pl.concat(dict_coeffs.values())#.cast(float)
# df_coeffs = df_coeffs.with_columns(pl.Series('coeff_combo', df_coeffs['coeff_combo'].cast(int)))
for c in coeff_names:
    df_coeffs = df_coeffs.with_columns(pl.Series(c, df_coeffs[c].cast(float)))

df_results = df_opt_results.join(df_coeffs, on='coeff_combo', how='left')

Calculate r-squared values of each fit:

In [ ]:
list_r2_dicts = []

for coeff_combo in df_results['coeff_combo']:
    dict_r2 = {}
    mask = df_results['coeff_combo'] == coeff_combo
    row_coeffs = df_results.filter(mask)

    df_admissions_here = df_stats[['MSOA', 'depriv_quantile_min', 'admissions'] + age_numbers]
    df_admissions_here = df_admissions_here.with_columns(pl.Series('admissions_predicted', np.zeros(len(df_admissions_here))))
    
    for q in qmin_list:
        qstr = str(round(q, 1)).replace('.', '')
        df_here = df_admissions_here.filter(df_admissions_here['depriv_quantile_min'] == q)
        
        for a in age_numbers:
            df_here = df_here.with_columns(pl.Series('admissions_predicted', df_here['admissions_predicted'] + (row_coeffs[f'{a}_q{qstr}'].to_numpy()[0] * df_here[a])))

        # R2 for just this q:
        r2_q = calculate_rsquared(df_here['admissions'], df_here['admissions_predicted'])
        dict_r2[f'r2_q{qstr}'] = np.round(r2_q, 5)
        
        mask = df_admissions_here['MSOA'].is_in(df_here['MSOA'])

        # df_admissions_here = df_admissions_here.with_columns(
        #    pl.when(mask)
        #      .then(df_here['admissions_predicted'])
        #      .otherwise(pl.col('admissions_predicted'))
        #      .name.keep()
        # )
        df_admissions_here = df_admissions_here.join(df_here['MSOA', 'admissions_predicted'], on='MSOA', suffix=f'_q{qstr}', how='left')
        
    cols_pred = [c for c in df_admissions_here.columns if (('q' in c) & (c.startswith('admissions_predicted')))]
    df_admissions_here = df_admissions_here.with_columns(pl.Series('admissions_predicted', df_admissions_here[cols_pred].sum_horizontal()))
    
    # Calculate R2:
    r2 = calculate_rsquared(df_admissions_here['admissions'], df_admissions_here['admissions_predicted'])
    dict_r2['r2_all'] = np.round(r2, 5)
    # Calculate residuals:
    res = find_square_residuals(df_admissions_here['admissions_predicted'], df_admissions_here['admissions'])
    dict_r2['res'] = np.round(res, 3)
            

    list_r2_dicts.append(pl.DataFrame([[coeff_combo] + list(dict_r2.values())], schema=['coeff_combo'] + list(dict_r2.keys())))

Convert results to dataframe:

In [ ]:
df_r2 = pl.concat(list_r2_dicts, how='vertical')

df_r2.sort('res')

Merge R2 results into main optimisation results:

In [ ]:
df_results_r2 = df_results.join(df_r2, on='coeff_combo', how='left')

In [ ]:
df_results_r2

In [ ]:
df_results_r2.write_csv(os.path.join('genetic_algorithms', 'outputs', 'post_deap_multi_optimise_coeffs_results.csv'))

## Annealing

Code to overwrite coeffs if only some combos should be run:

coeffs_init_start2 = {}
# i = 0
# for k, v in coeffs_init_start.items():
#     if i > 4:
#         coeffs_init_start2[k] = v
#     i += 1
# i = 0
for k, v in coeffs_init_start.items():
    if k in list(dict_coeffs.keys()):
        pass
    else:
        coeffs_init_start2[k] = v
coeffs_init_start = coeffs_init_start2

Run the annealing:

In [26]:
scales_init

array([1.2  , 1.2  , 1.2  , 1.1  , 1.304, 1.   , 1.1  , 1.1  , 1.037,
       1.092, 1.   , 1.026, 1.   , 1.   , 1.   , 0.9  , 0.9  , 0.9  ,
       0.9  , 0.9  , 0.9  , 0.9  , 0.883, 0.9  , 0.87 ])

In [27]:
dict_coeffs = {}
dict_opt_results = {}
# Store these opt results keys:
opt_results_keys = ['success', 'nit', 'minimization_failures', 'nfev']  # basin-hopping

i = 1
for coeff_combo, coeffs_init in coeffs_init_start.items():
# for coeff_combo, scales_init in scales_init_start.items():
    print(f'{i:5d} out of {len(coeffs_init_start)}', end='\r')
    # print(f'{i:5d} out of {len(scales_init_start)}', end='\r')
    i += 1

    # # Convert scales to coefficients:
    # coeffs_init = scales_init * np.concatenate([coeffs_ssnap] * 5)
    
    bounds_here = [(0.0, 1.0)] * len(coeffs_init)  # force results to lie between 0 and 1
    # bounds_here = [(0.0, 2.5)] * len(scales_init)  # force results to lie between 0 and 1
    
    # Run the optimiser:
    opt_results = basinhopping(
        main_opt,
        x0=coeffs_init,  # scales_init,  # coeffs_init,
        T=10.0,  # experiment
        stepsize=5e-5,  # 5e-5,
        minimizer_kwargs = dict(
            args=[all_x_lists, all_admissions, admissions_by_age],
            bounds=bounds_here,
            method='Nelder-Mead',
            options=dict(maxiter=10000),
            ),
    )
    # Pick out the resulting health coefficients:
    coeffs = np.round(opt_results['x'], 7)

    # Calculate R^2 here:

    # Log whether this combo optimised successfully:
    opt_results_to_save = [opt_results['message'][0]] + [opt_results[k] for k in opt_results_keys]
    # Log whether this combo optimised successfully:
    dict_opt_results[coeff_combo] = pl.DataFrame(np.array([[f'{coeff_combo}'] + opt_results_to_save]), schema=['coeff_combo', 'message'] + opt_results_keys)  # basin-hopping
    # pl.Series(f'{coeff_combo}', [opt_results[k] for k in opt_results_keys], strict=False).to_frame()
    # Store coeffs:
    dict_coeffs[coeff_combo] = pl.DataFrame(np.array([[f'{coeff_combo}'] + list(coeffs)]), schema=['coeff_combo'] + coeff_names)
    # pl.Series(f'{coeff_combo}', coeffs).to_frame()

/home/anna/miniconda3/envs/stroke_lsoa_prediction/lib/python3.10/site-packages/scipy/optimize/_basinhopping.py:294: OptimizeWarning: Initial guess is not within the specified bounds
  return self.minimizer(self.func, x0, **self.kwargs)

Gather results into dataFrames:

In [28]:
df_ann_opt_results = pl.concat(dict_opt_results.values())

df_ann_coeffs = pl.concat(dict_coeffs.values())
for c in coeff_names:
    df_ann_coeffs = df_ann_coeffs.with_columns(pl.Series(c, df_ann_coeffs[c].cast(float)))

df_ann_results = df_ann_opt_results.join(df_ann_coeffs, on='coeff_combo', how='left')

Calculate r-squared of results:

In [29]:
list_r2_dicts = []

for coeff_combo in df_ann_coeffs['coeff_combo']:
    dict_r2 = {}
    mask = df_ann_coeffs['coeff_combo'] == coeff_combo
    row_coeffs = df_ann_coeffs.filter(mask)

    df_admissions_here = df_stats[['MSOA', 'depriv_quantile_min', 'admissions'] + age_numbers]
    df_admissions_here = df_admissions_here.with_columns(pl.Series('admissions_predicted', np.zeros(len(df_admissions_here))))
    
    for q in qmin_list:
        qstr = str(round(q, 1)).replace('.', '')
        df_here = df_admissions_here.filter(df_admissions_here['depriv_quantile_min'] == q)
        
        for a in age_numbers:
            df_here = df_here.with_columns(pl.Series('admissions_predicted', df_here['admissions_predicted'] + (row_coeffs[f'{a}_q{qstr}'].to_numpy()[0] * df_here[a])))
            # df_here = df_here.with_columns(pl.Series('admissions_predicted', df_here['admissions_predicted'] + (row_coeffs[f'{a}_q{qstr}'].to_numpy()[0] * df_here[a])))

        # R2 for just this q:
        r2_q = calculate_rsquared(df_here['admissions'], df_here['admissions_predicted'])
        dict_r2[f'r2_q{qstr}'] = np.round(r2_q, 5)
        
        mask = df_admissions_here['MSOA'].is_in(df_here['MSOA'])

        # df_admissions_here = df_admissions_here.with_columns(
        #    pl.when(mask)
        #      .then(df_here['admissions_predicted'])
        #      .otherwise(pl.col('admissions_predicted'))
        #      .name.keep()
        # )
        df_admissions_here = df_admissions_here.join(df_here['MSOA', 'admissions_predicted'], on='MSOA', suffix=f'_q{qstr}', how='left')
        
    cols_pred = [c for c in df_admissions_here.columns if (('q' in c) & (c.startswith('admissions_predicted')))]
    df_admissions_here = df_admissions_here.with_columns(pl.Series('admissions_predicted', df_admissions_here[cols_pred].sum_horizontal()))
    
    # Calculate R2:
    r2 = calculate_rsquared(df_admissions_here['admissions'], df_admissions_here['admissions_predicted'])
    dict_r2['r2_all'] = np.round(r2, 5)
    # Calculate residuals:
    res = find_square_residuals(df_admissions_here['admissions_predicted'], df_admissions_here['admissions'])
    dict_r2['res'] = np.round(res, 3)
            

    list_r2_dicts.append(pl.DataFrame([[coeff_combo] + list(dict_r2.values())], schema=['coeff_combo'] + list(dict_r2.keys())))

Convert results to dataframe:

In [30]:
df_ann_r2 = pl.concat(list_r2_dicts, how='vertical')

Merge R2 results into main optimisation results:

In [31]:
df_ann_results = df_ann_results.join(df_ann_r2, on='coeff_combo', how='left')

In [32]:
df_ann_results

shape: (100, 38)
┌──────────────┬───────────────────────┬─────────┬─────┬───┬─────────┬─────────┬─────────┬─────────┐
│ coeff_combo  ┆ message               ┆ success ┆ nit ┆ … ┆ r2_q06  ┆ r2_q08  ┆ r2_all  ┆ res     │
│ ---          ┆ ---                   ┆ ---     ┆ --- ┆   ┆ ---     ┆ ---     ┆ ---     ┆ ---     │
│ str          ┆ str                   ┆ str     ┆ str ┆   ┆ f64     ┆ f64     ┆ f64     ┆ f64     │
╞══════════════╪═══════════════════════╪═════════╪═════╪═══╪═════════╪═════════╪═════════╪═════════╡
│ randomseed36 ┆ requested number of   ┆ True    ┆ 100 ┆ … ┆ 0.61611 ┆ 0.62451 ┆ 0.59608 ┆ 236.695 │
│              ┆ basinhoppi…           ┆         ┆     ┆   ┆         ┆         ┆         ┆         │
│ randomseed95 ┆ requested number of   ┆ True    ┆ 100 ┆ … ┆ 0.61639 ┆ 0.62035 ┆ 0.59599 ┆ 236.722 │
│              ┆ basinhoppi…           ┆         ┆     ┆   ┆         ┆         ┆         ┆         │
│ randomseed73 ┆ requested number of   ┆ True    ┆ 100 ┆ … ┆ 0.61842 ┆ 0.62263 ┆ 0.59651 ┆ 236.57  │
│              ┆ basinhoppi…           ┆         ┆     ┆   ┆         ┆         ┆         ┆         │
│ randomseed52 ┆ requested number of   ┆ True    ┆ 100 ┆ … ┆ 0.6181  ┆ 0.62087 ┆ 0.59661 ┆ 236.54  │
│              ┆ basinhoppi…           ┆         ┆     ┆   ┆         ┆         ┆         ┆         │
│ randomseed10 ┆ requested number of   ┆ True    ┆ 100 ┆ … ┆ 0.61802 ┆ 0.62084 ┆ 0.59636 ┆ 236.612 │
│              ┆ basinhoppi…           ┆         ┆     ┆   ┆         ┆         ┆         ┆         │
│ …            ┆ …                     ┆ …       ┆ …   ┆ … ┆ …       ┆ …       ┆ …       ┆ …       │
│ randomseed09 ┆ requested number of   ┆ True    ┆ 100 ┆ … ┆ 0.61852 ┆ 0.62473 ┆ 0.5965  ┆ 236.572 │
│              ┆ basinhoppi…           ┆         ┆     ┆   ┆         ┆         ┆         ┆         │
│ randomseed41 ┆ requested number of   ┆ True    ┆ 100 ┆ … ┆ 0.61962 ┆ 0.62475 ┆ 0.59649 ┆ 236.574 │
│              ┆ basinhoppi…           ┆         ┆     ┆   ┆         ┆         ┆         ┆         │
│ randomseed82 ┆ requested number of   ┆ True    ┆ 100 ┆ … ┆ 0.61834 ┆ 0.62164 ┆ 0.59625 ┆ 236.645 │
│              ┆ basinhoppi…           ┆         ┆     ┆   ┆         ┆         ┆         ┆         │
│ randomseed69 ┆ requested number of   ┆ True    ┆ 100 ┆ … ┆ 0.61718 ┆ 0.62385 ┆ 0.59668 ┆ 236.519 │
│              ┆ basinhoppi…           ┆         ┆     ┆   ┆         ┆         ┆         ┆         │
│ randomseed47 ┆ requested number of   ┆ True    ┆ 100 ┆ … ┆ 0.61866 ┆ 0.6257  ┆ 0.59573 ┆ 236.797 │
│              ┆ basinhoppi…           ┆         ┆     ┆   ┆         ┆         ┆         ┆         │
└──────────────┴───────────────────────┴─────────┴─────┴───┴─────────┴─────────┴─────────┴─────────┘

Save results:

In [33]:
df_ann_results.write_csv(os.path.join('genetic_algorithms', 'outputs', 'post_deap_multi_basinhop_coeffs_results.csv'))