## Optimise coeffs from DEAP output

In [39]:
import os
import polars as pl
from scipy.optimize import minimize, basinhopping
import numpy as np
import matplotlib.pyplot as plt

## Load data

Patient demographics by MSOA:

In [40]:
path_to_msoa_stats = os.path.join('data', 'msoa_cleaned.csv')

df_stats = pl.read_csv(path_to_msoa_stats)

In [41]:
df_stats.head()

shape: (5, 25)
┌──────────┬────────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ MSOA     ┆ admissions ┆ IMD2019Sc ┆ All       ┆ … ┆ age_75   ┆ age_over8 ┆ depriv_qu ┆ depriv_qu │
│ ---      ┆ ---        ┆ ore       ┆ persons   ┆   ┆ ---      ┆ 0         ┆ antile_mi ┆ antile_ma │
│ str      ┆ f64        ┆ ---       ┆ ---       ┆   ┆ f64      ┆ ---       ┆ n         ┆ x         │
│          ┆            ┆ f64       ┆ i64       ┆   ┆          ┆ f64       ┆ ---       ┆ ---       │
│          ┆            ┆           ┆           ┆   ┆          ┆           ┆ f64       ┆ f64       │
╞══════════╪════════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ Adur 001 ┆ 14.333333  ┆ 16.924833 ┆ 8815      ┆ … ┆ 359.7128 ┆ 528.488   ┆ 0.4       ┆ 0.6       │
│ Adur 002 ┆ 7.333333   ┆ 6.4704    ┆ 7263      ┆ … ┆ 326.3928 ┆ 459.0728  ┆ 0.8       ┆ 1.0       │
│ Adur 003 ┆ 9.333333   ┆ 13.7334   ┆ 7354      ┆ … ┆ 298.91   ┆ 469.31    ┆ 0.6       ┆ 0.8       │
│ Adur 004 ┆ 21.0       ┆ 26.199857 ┆ 10582     ┆ … ┆ 371.6609 ┆ 646.1026  ┆ 0.2       ┆ 0.4       │
│ Adur 005 ┆ 13.666667  ┆ 11.7948   ┆ 9059      ┆ … ┆ 362.355  ┆ 564.4212  ┆ 0.6       ┆ 0.8       │
└──────────┴────────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

Pick out column names for the health and age proportions:

In [42]:
health_numbers = ['good_health', 'fair health', 'bad health']
props_health = ['prop_good_health', 'prop_fair health', 'prop_bad health']
props_age = [
    'age_less65_proportion', 'age_65_proportion', 'age_70_proportion',
    'age_75_proportion', 'age_over80_proportion'
]
age_numbers = [p.replace('_proportion', '') for p in props_age]

In [43]:
qmin_list = sorted(df_stats['depriv_quantile_min'].unique())

In [44]:
# Names of coeffs:
coeff_names = [f'{a}_q{str(round(q, 1)).replace(".", "")}' for q in qmin_list for a in age_numbers]

coeff_names

['age_less65_q00',
 'age_65_q00',
 'age_70_q00',
 'age_75_q00',
 'age_over80_q00',
 'age_less65_q02',
 'age_65_q02',
 'age_70_q02',
 'age_75_q02',
 'age_over80_q02',
 'age_less65_q04',
 'age_65_q04',
 'age_70_q04',
 'age_75_q04',
 'age_over80_q04',
 'age_less65_q06',
 'age_65_q06',
 'age_70_q06',
 'age_75_q06',
 'age_over80_q06',
 'age_less65_q08',
 'age_65_q08',
 'age_70_q08',
 'age_75_q08',
 'age_over80_q08']

Pick out data for calculating admissions:

In [45]:
all_x_lists = []
all_admissions = []

for qmin in qmin_list:
    mask = (df_stats['depriv_quantile_min'] == qmin)
    # Keep only those MSOA:
    df_stats_here = df_stats.filter(mask)
    # MSOA data in the same order as those coefficients:
    x_lists = [df_stats_here[a] for a in age_numbers]
    admissions = df_stats_here['admissions'].to_numpy()
    all_x_lists.append(x_lists)
    all_admissions.append(admissions)

Starting SSNAP coefficients:

In [46]:
df_pop_admissions = pl.read_csv(os.path.join('outputs', 'ssnap_coeffs.csv'))

In [47]:
df_pop_admissions

shape: (5, 8)
┌────────────┬────────────┬────────────┬───────┬────────────┬────────────┬────────────┬────────────┐
│ Age Groups ┆ population ┆ prop_of_al ┆ count ┆ prop_of_al ┆ admissions ┆ admissions ┆ prob_strok │
│ ---        ┆ ---        ┆ l_pop      ┆ ---   ┆ l_admissio ┆ _annual    ┆ _annual_bo ┆ e_given_ag │
│ str        ┆ i64        ┆ ---        ┆ i64   ┆ ns         ┆ ---        ┆ ost        ┆ e          │
│            ┆            ┆ f64        ┆       ┆ ---        ┆ f64        ┆ ---        ┆ ---        │
│            ┆            ┆            ┆       ┆ f64        ┆            ┆ f64        ┆ f64        │
╞════════════╪════════════╪════════════╪═══════╪════════════╪════════════╪════════════╪════════════╡
│ Under 65   ┆ 45933245   ┆ 0.816055   ┆ 38827 ┆ 0.231449   ┆ 12942.3333 ┆ 18737.6681 ┆ 0.000408   │
│            ┆            ┆            ┆       ┆            ┆ 3          ┆ 9          ┆            │
│ 65-69      ┆ 2796740    ┆ 0.049687   ┆ 15324 ┆ 0.091347   ┆ 5108.0     ┆ 7395.26689 ┆ 0.002644   │
│ 70-74      ┆ 2779326    ┆ 0.049378   ┆ 21508 ┆ 0.12821    ┆ 7169.33333 ┆ 10379.6267 ┆ 0.003735   │
│            ┆            ┆            ┆       ┆            ┆            ┆ 4          ┆            │
│ 75-79      ┆ 1940686    ┆ 0.034478   ┆ 24150 ┆ 0.143959   ┆ 8050.0     ┆ 11654.6394 ┆ 0.006005   │
│            ┆            ┆            ┆       ┆            ┆            ┆ 8          ┆            │
│ 80 and     ┆ 2836964    ┆ 0.050402   ┆ 67947 ┆ 0.405035   ┆ 22649.0    ┆ 32790.7987 ┆ 0.011558   │
│ over       ┆            ┆            ┆       ┆            ┆            ┆            ┆            │
└────────────┴────────────┴────────────┴───────┴────────────┴────────────┴────────────┴────────────┘

Pick out SSNAP coefficients:

In [48]:
coeffs_ssnap = df_pop_admissions['prob_stroke_given_age'].to_numpy()

coeffs_ssnap

array([0.000408, 0.002644, 0.003735, 0.006005, 0.011558])

Pick out admissions numbers:

In [49]:
dict_admissions_age = dict(zip(df_pop_admissions['Age Groups'], df_pop_admissions['admissions_annual_boost']))

admissions_by_age = list(dict_admissions_age.values())

dict_admissions_age

{'Under 65': 18737.66819,
 '65-69': 7395.26689,
 '70-74': 10379.62674,
 '75-79': 11654.63948,
 '80 and over': 32790.7987}

## Gather starting coeffs

from best DEAP results

In [50]:
df_best_gens = pl.read_csv(os.path.join('outputs', 'best_inds_deap.csv'))

In [51]:
df_best_gens.sort('r2_all', descending=True)

shape: (100, 34)
┌──────────────┬───────┬──────────────┬────────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ dir          ┆ # gen ┆ age_less65_q ┆ age_65_q00 ┆ … ┆ r2_q02   ┆ r2_q04   ┆ r2_q06   ┆ r2_q08   │
│ ---          ┆ ---   ┆ 00           ┆ ---        ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str          ┆ f64   ┆ ---          ┆ f64        ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
│              ┆       ┆ f64          ┆            ┆   ┆          ┆          ┆          ┆          │
╞══════════════╪═══════╪══════════════╪════════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ randomseed04 ┆ 59.0  ┆ 1.46312      ┆ 1.695159   ┆ … ┆ 0.579529 ┆ 0.638646 ┆ 0.607951 ┆ 0.615709 │
│ randomseed41 ┆ 35.0  ┆ 1.4          ┆ 1.394472   ┆ … ┆ 0.58296  ┆ 0.634319 ┆ 0.606642 ┆ 0.619415 │
│ randomseed47 ┆ 51.0  ┆ 1.509935     ┆ 1.288461   ┆ … ┆ 0.579535 ┆ 0.634652 ┆ 0.607894 ┆ 0.620379 │
│ randomseed65 ┆ 58.0  ┆ 1.384298     ┆ 1.707645   ┆ … ┆ 0.581535 ┆ 0.635265 ┆ 0.605752 ┆ 0.619604 │
│ randomseed81 ┆ 30.0  ┆ 1.474497     ┆ 1.4        ┆ … ┆ 0.577989 ┆ 0.636342 ┆ 0.606189 ┆ 0.619144 │
│ …            ┆ …     ┆ …            ┆ …          ┆ … ┆ …        ┆ …        ┆ …        ┆ …        │
│ randomseed60 ┆ 23.0  ┆ 1.4          ┆ 1.391014   ┆ … ┆ 0.562332 ┆ 0.632282 ┆ 0.602063 ┆ 0.609088 │
│ randomseed83 ┆ 25.0  ┆ 1.322617     ┆ 1.350996   ┆ … ┆ 0.56937  ┆ 0.63435  ┆ 0.60288  ┆ 0.588041 │
│ randomseed98 ┆ 34.0  ┆ 1.4          ┆ 1.385308   ┆ … ┆ 0.578695 ┆ 0.63315  ┆ 0.605913 ┆ 0.585607 │
│ randomseed59 ┆ 22.0  ┆ 1.263284     ┆ 1.4        ┆ … ┆ 0.568264 ┆ 0.634055 ┆ 0.60606  ┆ 0.588969 │
│ randomseed97 ┆ 41.0  ┆ 1.395592     ┆ 1.4        ┆ … ┆ 0.565364 ┆ 0.632143 ┆ 0.606711 ┆ 0.578867 │
└──────────────┴───────┴──────────────┴────────────┴───┴──────────┴──────────┴──────────┴──────────┘

Pick out the directory names:

In [52]:
best_dirs = df_best_gens.sort('r2_all', descending=True)['dir'].to_numpy()

Pick out the coefficients for each of these directories:

In [53]:
# Store start combos of coeffs in here:
coeffs_init_start = {}

for d, best_dir in enumerate(best_dirs):
    scales_init = df_best_gens.filter(df_best_gens['dir'] == best_dir)[coeff_names].to_numpy()[0]
    coeffs_init = [s for s in scales_init]
    for c, coeff in enumerate(coeffs_ssnap):
        for i in range(5):
            coeffs_init[5*i + c] *= coeff
    coeffs_init_start[best_dir] = coeffs_init

# coeffs_init_grid = np.array(coeffs_init).reshape(5, 5)
# # To get all coeffs for one age band:        coeffs_init_grid[:, 0]
# # To get all coeffs for one depriv quantile: coeffs_init_grid[0, :]

Convert dictionary to dataframe:

In [54]:
df_coeffs_init = pl.concat([pl.DataFrame([c], schema=coeff_names) for c in coeffs_init_start.values()]).cast(float)

df_coeffs_init = df_coeffs_init.with_columns(pl.Series('coeff_combo', coeffs_init_start.keys()))#.cast(int))
# Move this column to start:
df_coeffs_init = df_coeffs_init.drop('coeff_combo').insert_column(0, df_coeffs_init.get_column('coeff_combo'))

Check results:

In [55]:
df_coeffs_init

shape: (100, 26)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ coeff_com ┆ age_less6 ┆ age_65_q0 ┆ age_70_q0 ┆ … ┆ age_65_q0 ┆ age_70_q0 ┆ age_75_q0 ┆ age_over │
│ bo        ┆ 5_q00     ┆ 0         ┆ 0         ┆   ┆ 8         ┆ 8         ┆ 8         ┆ 80_q08   │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ randomsee ┆ 0.000597  ┆ 0.004482  ┆ 0.004503  ┆ … ┆ 0.002099  ┆ 0.003361  ┆ 0.004804  ┆ 0.010753 │
│ d04       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ randomsee ┆ 0.0005712 ┆ 0.003687  ┆ 0.00557   ┆ … ┆ 0.002115  ┆ 0.002988  ┆ 0.005458  ┆ 0.011352 │
│ d41       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ randomsee ┆ 0.000616  ┆ 0.003407  ┆ 0.004956  ┆ … ┆ 0.002352  ┆ 0.003225  ┆ 0.004918  ┆ 0.011426 │
│ d47       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ randomsee ┆ 0.000565  ┆ 0.004515  ┆ 0.005976  ┆ … ┆ 0.0015864 ┆ 0.002607  ┆ 0.005822  ┆ 0.01135  │
│ d65       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ randomsee ┆ 0.000602  ┆ 0.003702  ┆ 0.005229  ┆ … ┆ 0.002091  ┆ 0.002988  ┆ 0.005577  ┆ 0.010991 │
│ d81       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ randomsee ┆ 0.0005712 ┆ 0.003678  ┆ 0.005229  ┆ … ┆ 0.002115  ┆ 0.002988  ┆ 0.004804  ┆ 0.010726 │
│ d60       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ randomsee ┆ 0.00054   ┆ 0.003572  ┆ 0.005011  ┆ … ┆ 0.001959  ┆ 0.002988  ┆ 0.004804  ┆ 0.010213 │
│ d83       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ randomsee ┆ 0.0005712 ┆ 0.003663  ┆ 0.004891  ┆ … ┆ 0.002137  ┆ 0.003398  ┆ 0.004804  ┆ 0.009687 │
│ d98       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ randomsee ┆ 0.000515  ┆ 0.003702  ┆ 0.005229  ┆ … ┆ 0.002115  ┆ 0.002988  ┆ 0.004804  ┆ 0.010119 │
│ d59       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ randomsee ┆ 0.000569  ┆ 0.003702  ┆ 0.004482  ┆ … ┆ 0.00229   ┆ 0.003396  ┆ 0.005096  ┆ 0.009246 │
│ d97       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

Save a copy:

In [56]:
df_coeffs_init.write_csv(os.path.join('genetic_algorithms', 'outputs', 'post_deap_inputs_for_opt.csv'))

## Function for optimising

In [97]:
def main_opt(coeffs, args):
    all_calculated_admissions = []
    all_observed_admissions = sum([list(a) for a in args[1]], [])

    coeffs = np.round(coeffs, 7)


    x_lists = args[0]
    admissions_by_age = args[2]
    # coeffs_ssnap = args[3]
    # Predictions for each age band across England:
    predictions_by_age = [0.0] * 5
    for i in range(5):
        # Population numbers for areas in this quantile:
        x_lists_here = x_lists[i]
        # Separate prediction for each deprivation quantile:
        coeffs_here = coeffs[(i*5):(i*5)+5] #* np.array(coeffs_ssnap)
        yhat_list = predict_admissions_each_age(x_lists_here, coeffs_here)
        # predictions_lists.append(yhat)
        for j, y in enumerate(yhat_list):
            predictions_by_age[j] += y
    # Divide the admissions by age band by the observed values:
    for j in range(len(predictions_by_age)):
        predictions_by_age[j] /= admissions_by_age[j]
    # Wrongness ratio factor:
    rat = sum(np.abs(np.array(predictions_by_age) - 1.0)) + 1.0

    
    coeffs_grid = np.array(coeffs).reshape(5, 5)
    for i, q in enumerate(qmin_list):
        coeffs_q = coeffs_grid[i, :]
        x_lists = args[0][i]
        admissions = args[1][i]
        
        calculated_admissions = predict_admissions(x_lists, np.array(coeffs_q))

        all_calculated_admissions += list(calculated_admissions)

    # Calculate measure of difference from the observed admissions:
    # print(
    #     np.array(all_calculated_admissions),
    #     np.array(all_observed_admissions)
    # )
    # diff = find_mean_abs_diff(
    diff = find_square_residuals(
        np.array(all_calculated_admissions),
        np.array(all_observed_admissions)
    )
    # Apply wrongness factor:
    diff *= rat

    
    diff_before = diff
    n_penalty = 0
    use_penalty = True
    if use_penalty:
        # Check coefficient conditions. If any aren't met, add a penalty
        # to the main difference measure.
        n_decrease = 0.0
        for i, q in enumerate(qmin_list):
            # Pick out coeffs for this depriv quantile:
            coeffs_q = coeffs_grid[i, :]
            # Do all coeffs increase with age band?
            n_decrease += sum(np.sign(np.diff(coeffs_q)) < 0)

        n_increase = 0.0
        for i, a in enumerate(age_numbers):
            # Pick out coeffs for this age band:
            coeffs_q = coeffs_grid[:, i]
            # Do all coeffs decrease with depriv quantile?
            n_increase += sum(np.sign(np.diff(coeffs_q)) > 0)

        # Add penalty:
        n_penalty = n_increase + n_decrease
        if n_penalty > 0.0:
            diff += (n_penalty * abs(diff) * 0.2)
    # print(diff_before, n_penalty, diff)
    # print(coeffs_grid)
    # # print(n_decrease, n_increase, diff)
    # print('\n' * 3)

    return diff

In [84]:
def predict_admissions(x_lists, coeffs):
    """
    x_lists: np.array.
    coeffs: np.array.
    
    Have to have same number of coeffs as x_lists.
    """
    # Predicted admissions:
    yhat = (x_lists * coeffs.reshape(len(coeffs), 1)).sum(axis=0)
    return yhat

In [85]:
def predict_admissions_each_age(x_lists, coeffs):
    """
    x_lists: np.array.
    coeffs: np.array.
    
    Have to have same number of coeffs as x_lists.
    """
    # Predicted admissions:
    # yhat = (x_lists * coeffs.reshape(len(coeffs), 1)).sum(axis=0)
    # yhat = [(x_lists[i] * coeffs[i]).to_numpy() for i in range(len(coeffs))]
    yhat = (
        [(x_lists[i] * coeffs[i]).sum() for i in range(len(coeffs))]
    )
    return yhat

Goodness check option 1: This calculates the sum of the square of the differences between predicted and actual admission numbers:

In [86]:
def find_square_residuals(yhat, y):
    # Difference from actual:
    sqres = (yhat - y)**2.0
    # Sum of differences:
    sum_sqres = np.sqrt(sqres.sum())
    return sum_sqres

Goodness check option 2: This calculates the mean absolute difference between the predicted and real admissions numbers:

In [87]:
def find_mean_abs_diff(yhat, y):
    # Difference from actual:
    absres = np.abs((yhat - y))
    # Mean of differences:
    mean_absres = absres.mean()
    return mean_absres

To check accuracy, the following function calculates R-squared:

In [88]:
def calculate_rsquared(y, yhat):
    """This gives the same results as the sklearn built-in."""
    y_mean = y.mean()
    ss_res = ((yhat - y)**2.0).sum()
    ss_tot = ((y - y_mean)**2.0).sum()
    if ss_tot != 0.0:
        rsq = 1.0 - ss_res / ss_tot
    else:
        rsq = np.NaN
    return rsq

## Run grid

In [ ]:
best_dirs = df_best_gens.filter(np.round(df_best_gens['r2_all'], 3) == np.round(df_best_gens['r2_all'].max(), 3))['dir'].to_numpy()

# Only run these best starting coeffs:
coeffs_init_start_opt = {}

for k, v in coeffs_init_start.items():
    if k in best_dirs:
        coeffs_init_start_opt[k] = v
    else:
        pass

In [98]:
dict_coeffs = {}
dict_opt_results = {}
# Store these opt results keys:
opt_results_keys = ['message', 'success', 'status', 'nit', 'nfev']

i = 1
for coeff_combo, coeffs_init in coeffs_init_start_opt.items():
    print(f'{i:5d} out of {len(coeffs_init_start_opt)}', end='\r')
    i += 1
    bounds_here = [(0.0, 1.0)] * len(coeffs_init)  # force results to lie between 0 and 1
    
        
    # Run the optimiser:
    opt_results = minimize(
        main_opt,
        x0=coeffs_init,
        args=[all_x_lists, all_admissions, admissions_by_age],
        bounds=bounds_here,
        method='Nelder-Mead',
        # method='SLSQP',
        options=dict(maxiter=10000),
    )
    # Pick out the resulting health coefficients:
    coeffs = np.round(opt_results['x'], 7)

    # Calculate R^2 here:

    # Log whether this combo optimised successfully:
    dict_opt_results[coeff_combo] = pl.DataFrame(np.array([[f'{coeff_combo}'] + [opt_results[k] for k in opt_results_keys]]), schema=['coeff_combo'] + opt_results_keys)
    # pl.Series(f'{coeff_combo}', [opt_results[k] for k in opt_results_keys], strict=False).to_frame()
    # Store coeffs:
    dict_coeffs[coeff_combo] = pl.DataFrame(np.array([[f'{coeff_combo}'] + list(coeffs)]), schema=['coeff_combo'] + coeff_names)
    # pl.Series(f'{coeff_combo}', coeffs).to_frame()

Gather results into dataFrames:

In [ ]:
df_opt_results = pl.concat(dict_opt_results.values())

df_coeffs = pl.concat(dict_coeffs.values())#.cast(float)
# df_coeffs = df_coeffs.with_columns(pl.Series('coeff_combo', df_coeffs['coeff_combo'].cast(int)))
for c in coeff_names:
    df_coeffs = df_coeffs.with_columns(pl.Series(c, df_coeffs[c].cast(float)))

df_results = df_opt_results.join(df_coeffs, on='coeff_combo', how='left')

Calculate r-squared values of each fit:

In [115]:
list_r2_dicts = []

for coeff_combo in df_results['coeff_combo']:
    dict_r2 = {}
    mask = df_results['coeff_combo'] == coeff_combo
    row_coeffs = df_results.filter(mask)

    df_admissions_here = df_stats[['MSOA', 'depriv_quantile_min', 'admissions'] + age_numbers]
    df_admissions_here = df_admissions_here.with_columns(pl.Series('admissions_predicted', np.zeros(len(df_admissions_here))))
    
    for q in qmin_list:
        qstr = str(round(q, 1)).replace('.', '')
        df_here = df_admissions_here.filter(df_admissions_here['depriv_quantile_min'] == q)
        
        for a in age_numbers:
            df_here = df_here.with_columns(pl.Series('admissions_predicted', df_here['admissions_predicted'] + (row_coeffs[f'{a}_q{qstr}'].to_numpy()[0] * df_here[a])))

        # R2 for just this q:
        r2_q = calculate_rsquared(df_here['admissions'], df_here['admissions_predicted'])
        dict_r2[f'r2_q{qstr}'] = np.round(r2_q, 5)
        
        mask = df_admissions_here['MSOA'].is_in(df_here['MSOA'])

        # df_admissions_here = df_admissions_here.with_columns(
        #    pl.when(mask)
        #      .then(df_here['admissions_predicted'])
        #      .otherwise(pl.col('admissions_predicted'))
        #      .name.keep()
        # )
        df_admissions_here = df_admissions_here.join(df_here['MSOA', 'admissions_predicted'], on='MSOA', suffix=f'_q{qstr}', how='left')
        
    cols_pred = [c for c in df_admissions_here.columns if (('q' in c) & (c.startswith('admissions_predicted')))]
    df_admissions_here = df_admissions_here.with_columns(pl.Series('admissions_predicted', df_admissions_here[cols_pred].sum_horizontal()))
    
    # Calculate R2:
    r2 = calculate_rsquared(df_admissions_here['admissions'], df_admissions_here['admissions_predicted'])
    dict_r2['r2_all'] = np.round(r2, 5)
    # Calculate residuals:
    res = find_square_residuals(df_admissions_here['admissions_predicted'], df_admissions_here['admissions'])
    dict_r2['res'] = np.round(res, 3)
            

    list_r2_dicts.append(pl.DataFrame([[coeff_combo] + list(dict_r2.values())], schema=['coeff_combo'] + list(dict_r2.keys())))

Convert results to dataframe:

In [ ]:
df_r2 = pl.concat(list_r2_dicts, how='vertical')

df_r2.sort('res')

Merge R2 results into main optimisation results:

In [119]:
df_results_r2 = df_results.join(df_r2, on='coeff_combo', how='left')

In [120]:
df_results_r2

shape: (5, 13)
┌──────────────┬────────────────────┬─────────┬────────┬───┬─────────┬─────────┬─────────┬─────────┐
│ coeff_combo  ┆ message            ┆ success ┆ status ┆ … ┆ r2_q06  ┆ r2_q08  ┆ r2_all  ┆ res     │
│ ---          ┆ ---                ┆ ---     ┆ ---    ┆   ┆ ---     ┆ ---     ┆ ---     ┆ ---     │
│ str          ┆ str                ┆ str     ┆ str    ┆   ┆ f64     ┆ f64     ┆ f64     ┆ f64     │
╞══════════════╪════════════════════╪═════════╪════════╪═══╪═════════╪═════════╪═════════╪═════════╡
│ randomseed04 ┆ Optimization       ┆ True    ┆ 0      ┆ … ┆ 0.60782 ┆ 0.61611 ┆ 0.59205 ┆ 237.872 │
│              ┆ terminated succes… ┆         ┆        ┆   ┆         ┆         ┆         ┆         │
│ randomseed41 ┆ Optimization       ┆ True    ┆ 0      ┆ … ┆ 0.60678 ┆ 0.61932 ┆ 0.59195 ┆ 237.901 │
│              ┆ terminated succes… ┆         ┆        ┆   ┆         ┆         ┆         ┆         │
│ randomseed47 ┆ Optimization       ┆ True    ┆ 0      ┆ … ┆ 0.60791 ┆ 0.62019 ┆ 0.59169 ┆ 237.978 │
│              ┆ terminated succes… ┆         ┆        ┆   ┆         ┆         ┆         ┆         │
│ randomseed65 ┆ Optimization       ┆ True    ┆ 0      ┆ … ┆ 0.60609 ┆ 0.62006 ┆ 0.59197 ┆ 237.897 │
│              ┆ terminated succes… ┆         ┆        ┆   ┆         ┆         ┆         ┆         │
│ randomseed81 ┆ Optimization       ┆ True    ┆ 0      ┆ … ┆ 0.60628 ┆ 0.61822 ┆ 0.59179 ┆ 237.95  │
│              ┆ terminated succes… ┆         ┆        ┆   ┆         ┆         ┆         ┆         │
└──────────────┴────────────────────┴─────────┴────────┴───┴─────────┴─────────┴─────────┴─────────┘

In [124]:
df_results_r2.write_csv(os.path.join('genetic_algorithms', 'outputs', 'post_deap_multi_optimise_coeffs_results.csv'))

## Annealing

Code to overwrite coeffs if only some combos should be run:

coeffs_init_start2 = {}
# i = 0
# for k, v in coeffs_init_start.items():
#     if i > 4:
#         coeffs_init_start2[k] = v
#     i += 1
# i = 0
for k, v in coeffs_init_start.items():
    if k in list(dict_coeffs.keys()):
        pass
    else:
        coeffs_init_start2[k] = v
coeffs_init_start = coeffs_init_start2

Run the annealing:

In [200]:
# dict_coeffs = {}
# dict_opt_results = {}
# Store these opt results keys:
opt_results_keys = ['success', 'nit', 'minimization_failures', 'nfev']  # basin-hopping

i = 1
for coeff_combo, coeffs_init in coeffs_init_start.items():
    print(f'{i:5d} out of {len(coeffs_init_start)}', end='\r')
    i += 1
    bounds_here = [(0.0, 1.0)] * len(coeffs_init)  # force results to lie between 0 and 1
    
    
    # Run the optimiser:
    opt_results = basinhopping(
        main_opt,
        x0=coeffs_init,
        T=30.0,  # experiment
        stepsize=5e-5,
        minimizer_kwargs = dict(
            args=[all_x_lists, all_admissions, admissions_by_age],
            # bounds=[(0.0, 1.0)] * len(age_coeffs),  # force results to lie between 0 and 1
            bounds=bounds_here,
            method='Nelder-Mead',
            options=dict(maxiter=10000),
            ),
    )
    # Pick out the resulting health coefficients:
    coeffs = np.round(opt_results['x'], 7)

    # Calculate R^2 here:

    # Log whether this combo optimised successfully:
    opt_results_to_save = [opt_results['message'][0]] + [opt_results[k] for k in opt_results_keys]
    # Log whether this combo optimised successfully:
    dict_opt_results[coeff_combo] = pl.DataFrame(np.array([[f'{coeff_combo}'] + opt_results_to_save]), schema=['coeff_combo', 'message'] + opt_results_keys)  # basin-hopping
    # pl.Series(f'{coeff_combo}', [opt_results[k] for k in opt_results_keys], strict=False).to_frame()
    # Store coeffs:
    dict_coeffs[coeff_combo] = pl.DataFrame(np.array([[f'{coeff_combo}'] + list(coeffs)]), schema=['coeff_combo'] + coeff_names)
    # pl.Series(f'{coeff_combo}', coeffs).to_frame()

Gather results into dataFrames:

In [ ]:
df_ann_opt_results = pl.concat(dict_opt_results.values())

df_ann_coeffs = pl.concat(dict_coeffs.values())
for c in coeff_names:
    df_ann_coeffs = df_ann_coeffs.with_columns(pl.Series(c, df_ann_coeffs[c].cast(float)))

df_ann_results = df_ann_opt_results.join(df_ann_coeffs, on='coeff_combo', how='left')

Calculate r-squared of results:

In [207]:
list_r2_dicts = []

for coeff_combo in df_ann_coeffs['coeff_combo']:
    dict_r2 = {}
    mask = df_ann_coeffs['coeff_combo'] == coeff_combo
    row_coeffs = df_ann_coeffs.filter(mask)

    df_admissions_here = df_stats[['MSOA', 'depriv_quantile_min', 'admissions'] + age_numbers]
    df_admissions_here = df_admissions_here.with_columns(pl.Series('admissions_predicted', np.zeros(len(df_admissions_here))))
    
    for q in qmin_list:
        qstr = str(round(q, 1)).replace('.', '')
        df_here = df_admissions_here.filter(df_admissions_here['depriv_quantile_min'] == q)
        
        for a in age_numbers:
            df_here = df_here.with_columns(pl.Series('admissions_predicted', df_here['admissions_predicted'] + (row_coeffs[f'{a}_q{qstr}'].to_numpy()[0] * df_here[a])))

        # R2 for just this q:
        r2_q = calculate_rsquared(df_here['admissions'], df_here['admissions_predicted'])
        dict_r2[f'r2_q{qstr}'] = np.round(r2_q, 5)
        
        mask = df_admissions_here['MSOA'].is_in(df_here['MSOA'])

        # df_admissions_here = df_admissions_here.with_columns(
        #    pl.when(mask)
        #      .then(df_here['admissions_predicted'])
        #      .otherwise(pl.col('admissions_predicted'))
        #      .name.keep()
        # )
        df_admissions_here = df_admissions_here.join(df_here['MSOA', 'admissions_predicted'], on='MSOA', suffix=f'_q{qstr}', how='left')
        
    cols_pred = [c for c in df_admissions_here.columns if (('q' in c) & (c.startswith('admissions_predicted')))]
    df_admissions_here = df_admissions_here.with_columns(pl.Series('admissions_predicted', df_admissions_here[cols_pred].sum_horizontal()))
    
    # Calculate R2:
    r2 = calculate_rsquared(df_admissions_here['admissions'], df_admissions_here['admissions_predicted'])
    dict_r2['r2_all'] = np.round(r2, 5)
    # Calculate residuals:
    res = find_square_residuals(df_admissions_here['admissions_predicted'], df_admissions_here['admissions'])
    dict_r2['res'] = np.round(res, 3)
            

    list_r2_dicts.append(pl.DataFrame([[coeff_combo] + list(dict_r2.values())], schema=['coeff_combo'] + list(dict_r2.keys())))

Convert results to dataframe:

In [208]:
df_ann_r2 = pl.concat(list_r2_dicts, how='vertical')

Merge R2 results into main optimisation results:

In [ ]:
df_ann_results = df_ann_results.join(df_ann_r2, on='coeff_combo', how='left')

Save results:

In [219]:
df_ann_results.write_csv(os.path.join('genetic_algorithms', 'outputs', 'post_deap_multi_basinhop_coeffs_results.csv'))